keys:
  - &hosts:
    - &nixie age1xn4y240a5r7n9ak2mmk3xrendsektn3mnk92vrvq4n4pl6hkp5pqc2jpn8

creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
        - *nixie
