keys:
  - &hosts:
    - &nixie age124axdmddma46lrf3gfx5td7z0k240adks9uyqynt8namj00yvy2satx57n

creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
        - *nixie
