keys:
  - &hosts:
    - &nixie age1j5n7rnrmen08v2gh258nvnwqnvaupcatn3ly90ez3m67fzmr7vns8kuvx7

creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
        - *nixie
