keys:
  - &hosts:
    - &nixie age1qja3q0krfx8rwj6leyng3p9h5hrvsefchypfs7ntyxjmwjvwtvgscdznq2

creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
        - *nixie
