keys:
  - &hosts '':
      - &nixie age1r5wkdzdjzd7zjyflue5d78qkr8uhwcvjmcwjaz9cx04kqplu7f3smwqwwu
      - &qemu age1r5wkdzdjzd7zjyflue5d78qkr8uhwcvjmcwjaz9cx04kqplu7f3smwqwwu
creation_rules:
  - path_regex: modules/users/secrets.ya?ml$
    key_groups:
      - age:
          - *nixie
          - *qemu
