#!/usr/bin/env bash

EWW_CMD=eww

$EWW_CMD close control-center-window-closer-0 control-center-window-closer-1 control-center-window-closer-2

$EWW_CMD update reveal-control-center="false" &
$EWW_CMD update reveal-session-menu="false" &
$EWW_CMD update reveal-volume-sinks="false" &
$EWW_CMD update reveal-volume-sources="false" &
