#!/usr/bin/env bash

EWW_CMD=eww
PRIMARY_MONITOR=2

# Open windows for each monitor
MONITORS=$(hyprctl monitors -j | jq '.[] | .id')
for monitor in ${MONITORS}; do
    ${EWW_CMD} open bottom-bar-${monitor} &
    ${EWW_CMD} open widgets-${monitor} &
done

scripts/hyprland &

${EWW_CMD} open control-center &
${EWW_CMD} open notification-popups &

# Reset notification mode
scripts/dbus-send --mode 0
