#!/usr/bin/env bash

STEP=5

if [ "$1" == "up" ]; then
	pamixer --increase ${STEP}
	canberra-gtk-play -f /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
elif [ "$1" == "down" ]; then
	pamixer --decrease ${STEP}
	canberra-gtk-play -f /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
else
	volume=$(pamixer --get-volume)
	new_volume=$1
	if [ $1 -lt $volume ] && [ $(($1 % 2)) -ne 0 ]; then
		new_volume=$(($1 - 1))
	elif [ $1 -gt $volume ] && [ $(($1 % 2)) -ne 0 ]; then
		new_volume=$(($1 + 1))
	fi
	pamixer --set-volume $new_volume

	canberra-gtk-play -f /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
fi
