#!/usr/bin/env bash

EWW_CMD=eww

result=$($EWW_CMD get expand-notification-groups)

if [[ $result == "true" ]]; then
    $EWW_CMD update expand-notification-groups="false" &
else
    $EWW_CMD update expand-notification-groups="true" &
fi
